// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mcp_service.proto

#include "mcp_service.pb.h"
#include "mcp_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace mcp {

static const char* MCPService_method_names[] = {
  "/mcp.MCPService/Register",
  "/mcp.MCPService/Initialize",
  "/mcp.MCPService/HandleRequest",
  "/mcp.MCPService/HandleNotification",
  "/mcp.MCPService/HandleBatchRequest",
  "/mcp.MCPService/RegisterInputSchema",
  "/mcp.MCPService/GetInputSchema",
  "/mcp.MCPService/ListResources",
  "/mcp.MCPService/ReadResource",
  "/mcp.MCPService/RegisterTool",
  "/mcp.MCPService/ListTools",
  "/mcp.MCPService/RegisterPrompt",
  "/mcp.MCPService/GetPrompt",
  "/mcp.MCPService/ListPrompts",
  "/mcp.MCPService/UpdatePrompt",
  "/mcp.MCPService/DeletePrompt",
};

std::unique_ptr< MCPService::Stub> MCPService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MCPService::Stub> stub(new MCPService::Stub(channel));
  return stub;
}

MCPService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Register_(MCPService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Initialize_(MCPService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HandleRequest_(MCPService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HandleNotification_(MCPService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HandleBatchRequest_(MCPService_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RegisterInputSchema_(MCPService_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetInputSchema_(MCPService_method_names[6], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListResources_(MCPService_method_names[7], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReadResource_(MCPService_method_names[8], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RegisterTool_(MCPService_method_names[9], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListTools_(MCPService_method_names[10], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RegisterPrompt_(MCPService_method_names[11], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPrompt_(MCPService_method_names[12], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListPrompts_(MCPService_method_names[13], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdatePrompt_(MCPService_method_names[14], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeletePrompt_(MCPService_method_names[15], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MCPService::Stub::Register(::grpc::ClientContext* context, const ::mcp::RegisterRequest& request, ::mcp::RegisterResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Register_, context, request, response);
}

void MCPService::Stub::experimental_async::Register(::grpc::ClientContext* context, const ::mcp::RegisterRequest* request, ::mcp::RegisterResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::mcp::RegisterResponse>* MCPService::Stub::AsyncRegisterRaw(::grpc::ClientContext* context, const ::mcp::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::RegisterResponse>::Create(channel_.get(), cq, rpcmethod_Register_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mcp::RegisterResponse>* MCPService::Stub::PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::mcp::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::RegisterResponse>::Create(channel_.get(), cq, rpcmethod_Register_, context, request, false);
}

::grpc::Status MCPService::Stub::Initialize(::grpc::ClientContext* context, const ::mcp::InitializeRequest& request, ::mcp::InitializeResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Initialize_, context, request, response);
}

void MCPService::Stub::experimental_async::Initialize(::grpc::ClientContext* context, const ::mcp::InitializeRequest* request, ::mcp::InitializeResult* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Initialize_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::mcp::InitializeResult>* MCPService::Stub::AsyncInitializeRaw(::grpc::ClientContext* context, const ::mcp::InitializeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::InitializeResult>::Create(channel_.get(), cq, rpcmethod_Initialize_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mcp::InitializeResult>* MCPService::Stub::PrepareAsyncInitializeRaw(::grpc::ClientContext* context, const ::mcp::InitializeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::InitializeResult>::Create(channel_.get(), cq, rpcmethod_Initialize_, context, request, false);
}

::grpc::Status MCPService::Stub::HandleRequest(::grpc::ClientContext* context, const ::mcp::JSONRPCRequest& request, ::mcp::JSONRPCResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_HandleRequest_, context, request, response);
}

void MCPService::Stub::experimental_async::HandleRequest(::grpc::ClientContext* context, const ::mcp::JSONRPCRequest* request, ::mcp::JSONRPCResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_HandleRequest_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::mcp::JSONRPCResponse>* MCPService::Stub::AsyncHandleRequestRaw(::grpc::ClientContext* context, const ::mcp::JSONRPCRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::JSONRPCResponse>::Create(channel_.get(), cq, rpcmethod_HandleRequest_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mcp::JSONRPCResponse>* MCPService::Stub::PrepareAsyncHandleRequestRaw(::grpc::ClientContext* context, const ::mcp::JSONRPCRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::JSONRPCResponse>::Create(channel_.get(), cq, rpcmethod_HandleRequest_, context, request, false);
}

::grpc::Status MCPService::Stub::HandleNotification(::grpc::ClientContext* context, const ::mcp::JSONRPCNotification& request, ::mcp::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_HandleNotification_, context, request, response);
}

void MCPService::Stub::experimental_async::HandleNotification(::grpc::ClientContext* context, const ::mcp::JSONRPCNotification* request, ::mcp::Empty* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_HandleNotification_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::mcp::Empty>* MCPService::Stub::AsyncHandleNotificationRaw(::grpc::ClientContext* context, const ::mcp::JSONRPCNotification& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::Empty>::Create(channel_.get(), cq, rpcmethod_HandleNotification_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mcp::Empty>* MCPService::Stub::PrepareAsyncHandleNotificationRaw(::grpc::ClientContext* context, const ::mcp::JSONRPCNotification& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::Empty>::Create(channel_.get(), cq, rpcmethod_HandleNotification_, context, request, false);
}

::grpc::Status MCPService::Stub::HandleBatchRequest(::grpc::ClientContext* context, const ::mcp::JSONRPCBatchRequest& request, ::mcp::JSONRPCBatchResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_HandleBatchRequest_, context, request, response);
}

void MCPService::Stub::experimental_async::HandleBatchRequest(::grpc::ClientContext* context, const ::mcp::JSONRPCBatchRequest* request, ::mcp::JSONRPCBatchResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_HandleBatchRequest_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::mcp::JSONRPCBatchResponse>* MCPService::Stub::AsyncHandleBatchRequestRaw(::grpc::ClientContext* context, const ::mcp::JSONRPCBatchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::JSONRPCBatchResponse>::Create(channel_.get(), cq, rpcmethod_HandleBatchRequest_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mcp::JSONRPCBatchResponse>* MCPService::Stub::PrepareAsyncHandleBatchRequestRaw(::grpc::ClientContext* context, const ::mcp::JSONRPCBatchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::JSONRPCBatchResponse>::Create(channel_.get(), cq, rpcmethod_HandleBatchRequest_, context, request, false);
}

::grpc::Status MCPService::Stub::RegisterInputSchema(::grpc::ClientContext* context, const ::mcp::RegisterInputSchemaRequest& request, ::mcp::RegisterInputSchemaResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RegisterInputSchema_, context, request, response);
}

void MCPService::Stub::experimental_async::RegisterInputSchema(::grpc::ClientContext* context, const ::mcp::RegisterInputSchemaRequest* request, ::mcp::RegisterInputSchemaResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RegisterInputSchema_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::mcp::RegisterInputSchemaResponse>* MCPService::Stub::AsyncRegisterInputSchemaRaw(::grpc::ClientContext* context, const ::mcp::RegisterInputSchemaRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::RegisterInputSchemaResponse>::Create(channel_.get(), cq, rpcmethod_RegisterInputSchema_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mcp::RegisterInputSchemaResponse>* MCPService::Stub::PrepareAsyncRegisterInputSchemaRaw(::grpc::ClientContext* context, const ::mcp::RegisterInputSchemaRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::RegisterInputSchemaResponse>::Create(channel_.get(), cq, rpcmethod_RegisterInputSchema_, context, request, false);
}

::grpc::Status MCPService::Stub::GetInputSchema(::grpc::ClientContext* context, const ::mcp::GetInputSchemaRequest& request, ::mcp::InputSchema* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetInputSchema_, context, request, response);
}

void MCPService::Stub::experimental_async::GetInputSchema(::grpc::ClientContext* context, const ::mcp::GetInputSchemaRequest* request, ::mcp::InputSchema* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetInputSchema_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::mcp::InputSchema>* MCPService::Stub::AsyncGetInputSchemaRaw(::grpc::ClientContext* context, const ::mcp::GetInputSchemaRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::InputSchema>::Create(channel_.get(), cq, rpcmethod_GetInputSchema_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mcp::InputSchema>* MCPService::Stub::PrepareAsyncGetInputSchemaRaw(::grpc::ClientContext* context, const ::mcp::GetInputSchemaRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::InputSchema>::Create(channel_.get(), cq, rpcmethod_GetInputSchema_, context, request, false);
}

::grpc::Status MCPService::Stub::ListResources(::grpc::ClientContext* context, const ::mcp::ListResourcesRequest& request, ::mcp::ListResourcesResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ListResources_, context, request, response);
}

void MCPService::Stub::experimental_async::ListResources(::grpc::ClientContext* context, const ::mcp::ListResourcesRequest* request, ::mcp::ListResourcesResult* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ListResources_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::mcp::ListResourcesResult>* MCPService::Stub::AsyncListResourcesRaw(::grpc::ClientContext* context, const ::mcp::ListResourcesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::ListResourcesResult>::Create(channel_.get(), cq, rpcmethod_ListResources_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mcp::ListResourcesResult>* MCPService::Stub::PrepareAsyncListResourcesRaw(::grpc::ClientContext* context, const ::mcp::ListResourcesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::ListResourcesResult>::Create(channel_.get(), cq, rpcmethod_ListResources_, context, request, false);
}

::grpc::Status MCPService::Stub::ReadResource(::grpc::ClientContext* context, const ::mcp::ReadResourceRequest& request, ::mcp::ReadResourceResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ReadResource_, context, request, response);
}

void MCPService::Stub::experimental_async::ReadResource(::grpc::ClientContext* context, const ::mcp::ReadResourceRequest* request, ::mcp::ReadResourceResult* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ReadResource_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::mcp::ReadResourceResult>* MCPService::Stub::AsyncReadResourceRaw(::grpc::ClientContext* context, const ::mcp::ReadResourceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::ReadResourceResult>::Create(channel_.get(), cq, rpcmethod_ReadResource_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mcp::ReadResourceResult>* MCPService::Stub::PrepareAsyncReadResourceRaw(::grpc::ClientContext* context, const ::mcp::ReadResourceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::ReadResourceResult>::Create(channel_.get(), cq, rpcmethod_ReadResource_, context, request, false);
}

::grpc::Status MCPService::Stub::RegisterTool(::grpc::ClientContext* context, const ::mcp::RegisterToolRequest& request, ::mcp::RegisterToolResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RegisterTool_, context, request, response);
}

void MCPService::Stub::experimental_async::RegisterTool(::grpc::ClientContext* context, const ::mcp::RegisterToolRequest* request, ::mcp::RegisterToolResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RegisterTool_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::mcp::RegisterToolResponse>* MCPService::Stub::AsyncRegisterToolRaw(::grpc::ClientContext* context, const ::mcp::RegisterToolRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::RegisterToolResponse>::Create(channel_.get(), cq, rpcmethod_RegisterTool_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mcp::RegisterToolResponse>* MCPService::Stub::PrepareAsyncRegisterToolRaw(::grpc::ClientContext* context, const ::mcp::RegisterToolRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::RegisterToolResponse>::Create(channel_.get(), cq, rpcmethod_RegisterTool_, context, request, false);
}

::grpc::Status MCPService::Stub::ListTools(::grpc::ClientContext* context, const ::mcp::ListToolsRequest& request, ::mcp::ListToolsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ListTools_, context, request, response);
}

void MCPService::Stub::experimental_async::ListTools(::grpc::ClientContext* context, const ::mcp::ListToolsRequest* request, ::mcp::ListToolsResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ListTools_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::mcp::ListToolsResponse>* MCPService::Stub::AsyncListToolsRaw(::grpc::ClientContext* context, const ::mcp::ListToolsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::ListToolsResponse>::Create(channel_.get(), cq, rpcmethod_ListTools_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mcp::ListToolsResponse>* MCPService::Stub::PrepareAsyncListToolsRaw(::grpc::ClientContext* context, const ::mcp::ListToolsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::ListToolsResponse>::Create(channel_.get(), cq, rpcmethod_ListTools_, context, request, false);
}

::grpc::Status MCPService::Stub::RegisterPrompt(::grpc::ClientContext* context, const ::mcp::RegisterPromptRequest& request, ::mcp::RegisterPromptResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RegisterPrompt_, context, request, response);
}

void MCPService::Stub::experimental_async::RegisterPrompt(::grpc::ClientContext* context, const ::mcp::RegisterPromptRequest* request, ::mcp::RegisterPromptResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RegisterPrompt_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::mcp::RegisterPromptResponse>* MCPService::Stub::AsyncRegisterPromptRaw(::grpc::ClientContext* context, const ::mcp::RegisterPromptRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::RegisterPromptResponse>::Create(channel_.get(), cq, rpcmethod_RegisterPrompt_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mcp::RegisterPromptResponse>* MCPService::Stub::PrepareAsyncRegisterPromptRaw(::grpc::ClientContext* context, const ::mcp::RegisterPromptRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::RegisterPromptResponse>::Create(channel_.get(), cq, rpcmethod_RegisterPrompt_, context, request, false);
}

::grpc::Status MCPService::Stub::GetPrompt(::grpc::ClientContext* context, const ::mcp::GetPromptRequest& request, ::mcp::Prompt* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetPrompt_, context, request, response);
}

void MCPService::Stub::experimental_async::GetPrompt(::grpc::ClientContext* context, const ::mcp::GetPromptRequest* request, ::mcp::Prompt* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetPrompt_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::mcp::Prompt>* MCPService::Stub::AsyncGetPromptRaw(::grpc::ClientContext* context, const ::mcp::GetPromptRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::Prompt>::Create(channel_.get(), cq, rpcmethod_GetPrompt_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mcp::Prompt>* MCPService::Stub::PrepareAsyncGetPromptRaw(::grpc::ClientContext* context, const ::mcp::GetPromptRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::Prompt>::Create(channel_.get(), cq, rpcmethod_GetPrompt_, context, request, false);
}

::grpc::Status MCPService::Stub::ListPrompts(::grpc::ClientContext* context, const ::mcp::ListPromptsRequest& request, ::mcp::ListPromptsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ListPrompts_, context, request, response);
}

void MCPService::Stub::experimental_async::ListPrompts(::grpc::ClientContext* context, const ::mcp::ListPromptsRequest* request, ::mcp::ListPromptsResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ListPrompts_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::mcp::ListPromptsResponse>* MCPService::Stub::AsyncListPromptsRaw(::grpc::ClientContext* context, const ::mcp::ListPromptsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::ListPromptsResponse>::Create(channel_.get(), cq, rpcmethod_ListPrompts_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mcp::ListPromptsResponse>* MCPService::Stub::PrepareAsyncListPromptsRaw(::grpc::ClientContext* context, const ::mcp::ListPromptsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::ListPromptsResponse>::Create(channel_.get(), cq, rpcmethod_ListPrompts_, context, request, false);
}

::grpc::Status MCPService::Stub::UpdatePrompt(::grpc::ClientContext* context, const ::mcp::UpdatePromptRequest& request, ::mcp::UpdatePromptResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_UpdatePrompt_, context, request, response);
}

void MCPService::Stub::experimental_async::UpdatePrompt(::grpc::ClientContext* context, const ::mcp::UpdatePromptRequest* request, ::mcp::UpdatePromptResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UpdatePrompt_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::mcp::UpdatePromptResponse>* MCPService::Stub::AsyncUpdatePromptRaw(::grpc::ClientContext* context, const ::mcp::UpdatePromptRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::UpdatePromptResponse>::Create(channel_.get(), cq, rpcmethod_UpdatePrompt_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mcp::UpdatePromptResponse>* MCPService::Stub::PrepareAsyncUpdatePromptRaw(::grpc::ClientContext* context, const ::mcp::UpdatePromptRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::UpdatePromptResponse>::Create(channel_.get(), cq, rpcmethod_UpdatePrompt_, context, request, false);
}

::grpc::Status MCPService::Stub::DeletePrompt(::grpc::ClientContext* context, const ::mcp::DeletePromptRequest& request, ::mcp::DeletePromptResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_DeletePrompt_, context, request, response);
}

void MCPService::Stub::experimental_async::DeletePrompt(::grpc::ClientContext* context, const ::mcp::DeletePromptRequest* request, ::mcp::DeletePromptResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DeletePrompt_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::mcp::DeletePromptResponse>* MCPService::Stub::AsyncDeletePromptRaw(::grpc::ClientContext* context, const ::mcp::DeletePromptRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::DeletePromptResponse>::Create(channel_.get(), cq, rpcmethod_DeletePrompt_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mcp::DeletePromptResponse>* MCPService::Stub::PrepareAsyncDeletePromptRaw(::grpc::ClientContext* context, const ::mcp::DeletePromptRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::mcp::DeletePromptResponse>::Create(channel_.get(), cq, rpcmethod_DeletePrompt_, context, request, false);
}

MCPService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MCPService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MCPService::Service, ::mcp::RegisterRequest, ::mcp::RegisterResponse>(
          std::mem_fn(&MCPService::Service::Register), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MCPService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MCPService::Service, ::mcp::InitializeRequest, ::mcp::InitializeResult>(
          std::mem_fn(&MCPService::Service::Initialize), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MCPService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MCPService::Service, ::mcp::JSONRPCRequest, ::mcp::JSONRPCResponse>(
          std::mem_fn(&MCPService::Service::HandleRequest), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MCPService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MCPService::Service, ::mcp::JSONRPCNotification, ::mcp::Empty>(
          std::mem_fn(&MCPService::Service::HandleNotification), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MCPService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MCPService::Service, ::mcp::JSONRPCBatchRequest, ::mcp::JSONRPCBatchResponse>(
          std::mem_fn(&MCPService::Service::HandleBatchRequest), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MCPService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MCPService::Service, ::mcp::RegisterInputSchemaRequest, ::mcp::RegisterInputSchemaResponse>(
          std::mem_fn(&MCPService::Service::RegisterInputSchema), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MCPService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MCPService::Service, ::mcp::GetInputSchemaRequest, ::mcp::InputSchema>(
          std::mem_fn(&MCPService::Service::GetInputSchema), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MCPService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MCPService::Service, ::mcp::ListResourcesRequest, ::mcp::ListResourcesResult>(
          std::mem_fn(&MCPService::Service::ListResources), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MCPService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MCPService::Service, ::mcp::ReadResourceRequest, ::mcp::ReadResourceResult>(
          std::mem_fn(&MCPService::Service::ReadResource), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MCPService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MCPService::Service, ::mcp::RegisterToolRequest, ::mcp::RegisterToolResponse>(
          std::mem_fn(&MCPService::Service::RegisterTool), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MCPService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MCPService::Service, ::mcp::ListToolsRequest, ::mcp::ListToolsResponse>(
          std::mem_fn(&MCPService::Service::ListTools), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MCPService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MCPService::Service, ::mcp::RegisterPromptRequest, ::mcp::RegisterPromptResponse>(
          std::mem_fn(&MCPService::Service::RegisterPrompt), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MCPService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MCPService::Service, ::mcp::GetPromptRequest, ::mcp::Prompt>(
          std::mem_fn(&MCPService::Service::GetPrompt), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MCPService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MCPService::Service, ::mcp::ListPromptsRequest, ::mcp::ListPromptsResponse>(
          std::mem_fn(&MCPService::Service::ListPrompts), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MCPService_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MCPService::Service, ::mcp::UpdatePromptRequest, ::mcp::UpdatePromptResponse>(
          std::mem_fn(&MCPService::Service::UpdatePrompt), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MCPService_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MCPService::Service, ::mcp::DeletePromptRequest, ::mcp::DeletePromptResponse>(
          std::mem_fn(&MCPService::Service::DeletePrompt), this)));
}

MCPService::Service::~Service() {
}

::grpc::Status MCPService::Service::Register(::grpc::ServerContext* context, const ::mcp::RegisterRequest* request, ::mcp::RegisterResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MCPService::Service::Initialize(::grpc::ServerContext* context, const ::mcp::InitializeRequest* request, ::mcp::InitializeResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MCPService::Service::HandleRequest(::grpc::ServerContext* context, const ::mcp::JSONRPCRequest* request, ::mcp::JSONRPCResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MCPService::Service::HandleNotification(::grpc::ServerContext* context, const ::mcp::JSONRPCNotification* request, ::mcp::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MCPService::Service::HandleBatchRequest(::grpc::ServerContext* context, const ::mcp::JSONRPCBatchRequest* request, ::mcp::JSONRPCBatchResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MCPService::Service::RegisterInputSchema(::grpc::ServerContext* context, const ::mcp::RegisterInputSchemaRequest* request, ::mcp::RegisterInputSchemaResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MCPService::Service::GetInputSchema(::grpc::ServerContext* context, const ::mcp::GetInputSchemaRequest* request, ::mcp::InputSchema* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MCPService::Service::ListResources(::grpc::ServerContext* context, const ::mcp::ListResourcesRequest* request, ::mcp::ListResourcesResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MCPService::Service::ReadResource(::grpc::ServerContext* context, const ::mcp::ReadResourceRequest* request, ::mcp::ReadResourceResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MCPService::Service::RegisterTool(::grpc::ServerContext* context, const ::mcp::RegisterToolRequest* request, ::mcp::RegisterToolResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MCPService::Service::ListTools(::grpc::ServerContext* context, const ::mcp::ListToolsRequest* request, ::mcp::ListToolsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MCPService::Service::RegisterPrompt(::grpc::ServerContext* context, const ::mcp::RegisterPromptRequest* request, ::mcp::RegisterPromptResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MCPService::Service::GetPrompt(::grpc::ServerContext* context, const ::mcp::GetPromptRequest* request, ::mcp::Prompt* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MCPService::Service::ListPrompts(::grpc::ServerContext* context, const ::mcp::ListPromptsRequest* request, ::mcp::ListPromptsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MCPService::Service::UpdatePrompt(::grpc::ServerContext* context, const ::mcp::UpdatePromptRequest* request, ::mcp::UpdatePromptResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MCPService::Service::DeletePrompt(::grpc::ServerContext* context, const ::mcp::DeletePromptRequest* request, ::mcp::DeletePromptResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mcp

